### ISSUE TITLE
Icons in context menu not up to date

### ISSUE THREAD

**Issue by sbhklr** [arduino/Arduino-Science-Journal-Android#15]
**Describe the bug**
The icons in the context menu of the experiment are outdated.

**Expected behavior**
The new ones from the design template should be used instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/1326220/92897689-b2d8c100-f41d-11ea-8f50-966b1a43427e.png)

**Smartphone (please complete the following information):**
 - OS: Android

**Comment by h42-carlopelliccia** [comment]
fixed in 1.0.1

**Comment by sbhklr** [comment]
A release containing a fix for this has been shipped.
